class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start50'
        self.MirrorCommand = 'mir50'
        self.UnzipMirrorCommand = 'unzipmir50'
        self.TarMirrorCommand = 'tarmir50'
        self.ZipMirrorCommand = 'zipmir50'
        self.CancelMirror = 'cancel50'
        self.CancelAllCommand = 'cancelall50'
        self.ListCommand = 'list50'
        self.StatusCommand = 'status50'
        self.AuthorizedUsersCommand = 'users50'
        self.AuthorizeCommand = 'auth50'
        self.UnAuthorizeCommand = 'unauth50'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping50'
        self.RestartCommand = 'restart50'
        self.StatsCommand = 'stats50'
        self.HelpCommand = 'help50'
        self.LogCommand = 'log50'
        self.SpeedCommand = 'speedtest50'
        self.CloneCommand = 'clone50'
        self.CountCommand = 'count50'
        self.WatchCommand = 'watch50'
        self.TarWatchCommand = 'tarwatch50'
        self.DeleteCommand = 'del50'
        self.ShellCommand = 'shell50'
        self.ExecHelpCommand = 'exechelp50'
        self.TsHelpCommand = 'tshelp50'

BotCommands = _BotCommands()
